// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.1.22076.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("backend.Models.CoordinateIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoordinateIndexes", (string)null);
                });

            modelBuilder.Entity("backend.Models.RouteCoordinate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Centered")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("UserRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRouteId");

                    b.ToTable("RouteCoordinates", (string)null);
                });

            modelBuilder.Entity("backend.Models.StaticRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Index1")
                        .HasColumnType("float");

                    b.Property<double>("Index2")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Index1", "Index2");

                    b.ToTable("StaticRegions", (string)null);
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AccessExpiresDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("backend.Models.UserActivitiesCloseBy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActivitiesCloseBy", (string)null);
                });

            modelBuilder.Entity("Backend.Models.UserActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("ActivityStatus")
                        .HasColumnType("int");

                    b.Property<float>("AverageSpeed")
                        .HasColumnType("real");

                    b.Property<int?>("AveragedRouteId")
                        .HasColumnType("int");

                    b.Property<int?>("CenteredRouteId")
                        .HasColumnType("int");

                    b.Property<float>("Distance")
                        .HasColumnType("real");

                    b.Property<float>("ElapsedTime")
                        .HasColumnType("real");

                    b.Property<float>("ElevationGain")
                        .HasColumnType("real");

                    b.Property<float>("MaxSpeed")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RawRouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StravaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AveragedRouteId");

                    b.HasIndex("CenteredRouteId");

                    b.HasIndex("RawRouteId");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivities", (string)null);
                });

            modelBuilder.Entity("backend.Models.UserActivityCloseBy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserActivitiesCloseById")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserActivitiesCloseById");

                    b.ToTable("ActivityCloseBy", (string)null);
                });

            modelBuilder.Entity("backend.Models.UserRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("UserRoutes", (string)null);
                });

            modelBuilder.Entity("CoordinateIndexRouteCoordinate", b =>
                {
                    b.Property<int>("CoordinateIndexesId")
                        .HasColumnType("int");

                    b.Property<long>("RouteCoordinateId")
                        .HasColumnType("bigint");

                    b.HasKey("CoordinateIndexesId", "RouteCoordinateId");

                    b.HasIndex("RouteCoordinateId");

                    b.ToTable("CoordinateIndexRouteCoordinate", (string)null);
                });

            modelBuilder.Entity("StaticRegionUserActivity", b =>
                {
                    b.Property<int>("RegionsId")
                        .HasColumnType("int");

                    b.Property<long>("UserActivitiesId")
                        .HasColumnType("bigint");

                    b.HasKey("RegionsId", "UserActivitiesId");

                    b.HasIndex("UserActivitiesId");

                    b.ToTable("StaticRegionUserActivity", (string)null);
                });

            modelBuilder.Entity("backend.Models.RouteCoordinate", b =>
                {
                    b.HasOne("backend.Models.UserRoute", "UserRoute")
                        .WithMany("RouteCoordinates")
                        .HasForeignKey("UserRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRoute");
                });

            modelBuilder.Entity("backend.Models.UserActivitiesCloseBy", b =>
                {
                    b.HasOne("backend.Models.User", null)
                        .WithMany("ActivitiesCloseBy")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Backend.Models.UserActivity", b =>
                {
                    b.HasOne("backend.Models.UserRoute", "AveragedRoute")
                        .WithMany()
                        .HasForeignKey("AveragedRouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.UserRoute", "CenteredRoute")
                        .WithMany()
                        .HasForeignKey("CenteredRouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.UserRoute", "RawRoute")
                        .WithMany()
                        .HasForeignKey("RawRouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AveragedRoute");

                    b.Navigation("CenteredRoute");

                    b.Navigation("RawRoute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.UserActivityCloseBy", b =>
                {
                    b.HasOne("backend.Models.UserActivitiesCloseBy", "UserActivitiesCloseBy")
                        .WithMany("ActivityIds")
                        .HasForeignKey("UserActivitiesCloseById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserActivitiesCloseBy");
                });

            modelBuilder.Entity("CoordinateIndexRouteCoordinate", b =>
                {
                    b.HasOne("backend.Models.CoordinateIndex", null)
                        .WithMany()
                        .HasForeignKey("CoordinateIndexesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.RouteCoordinate", null)
                        .WithMany()
                        .HasForeignKey("RouteCoordinateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaticRegionUserActivity", b =>
                {
                    b.HasOne("backend.Models.StaticRegion", null)
                        .WithMany()
                        .HasForeignKey("RegionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.UserActivity", null)
                        .WithMany()
                        .HasForeignKey("UserActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ActivitiesCloseBy");
                });

            modelBuilder.Entity("backend.Models.UserActivitiesCloseBy", b =>
                {
                    b.Navigation("ActivityIds");
                });

            modelBuilder.Entity("backend.Models.UserRoute", b =>
                {
                    b.Navigation("RouteCoordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
